### ISSUE TITLE
PS2 is no show in my datahub. 

### ISSUE THREAD

**Issue by Averysaurus** [PHW290/PHW290_Fall2020#1]
Can I just use the repo to complete assignment? ~Avery

**Comment by lytello** [comment]
Hi Avery,

You’re welcome to use your desktop version if you like. However, if you run into errors that require us to peak at your rstudio cloud we ask that you put your markdown file onto datahub.

The assignment should be on datahub so long as you use the link. If it isn’t working for you it’s helpful for me to know! I know one other student was able to access the assignment.

Best,
Lawrence

—
Lawrence Y. Tello
Pronouns: he/him/his
MPH Candidate 2021 in Epidemiology/Biostatistics
UC Berkeley School of Public Health
lytello@berkeley.edu | LinkedIn
